spring.application.name=springboot-jpa

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=db_springboot;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Admin1234@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update