
config.code=12345
config.username=jmorales
config.message=Hola Mundo - áñ
config.listOfValues=uno,dos,tres,cuatro
config.valuesMap={product: 'CPU Intel Core i7', description: 'Procesador I7 12th', price: 299.99}